In [1]:
import torch

x = torch.arange(12)

print("Original")
print(x)
print(x.shape)

x = x.reshape(3,4)

print("\nReshape")
print(x)
print(x.shape)

x = x.flatten()

print("\nFlatten")
print(x)
print(x.shape)

Original
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])

Reshape
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])

Flatten
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])


In [2]:
import torch

x = torch.arange(8)

y = x.reshape(2,4)

z = y.flatten()

print(y)
print(y.shape)
print(z.shape)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
torch.Size([2, 4])
torch.Size([8])
