In [1]:
import tensorflow as tf

In [2]:
tfc = tf.constant(1)
tfc

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [3]:
tf.constant(2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [4]:
tfc = tf.constant(1)
tfc
tf.constant(2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>