In [1]:
import tensorflow as tf

print(tf.__version__)

2.21.0


In [2]:
import tensorflow as tf

a = tf.constant(10)
b = tf.constant(20)

c = a + b

print(c)

tf.Tensor(30, shape=(), dtype=int32)


In [3]:
print(c.numpy())

30


In [4]:
from tensorflow import keras

model = keras.Sequential([
    keras.layers.Dense(10, input_shape=(5,))
])

print("Model Created")

Model Created


C:\Users\shubh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [5]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 10)                  │              60 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 60 (240.00 B)

 Trainable params: 60 (240.00 B)

 Non-trainable params: 0 (0.00 B)

In [6]:
import numpy as np

print(np.__version__)

1.26.4


In [7]:
import numpy as np
import tensorflow as tf

# NumPy array create karna
arr = np.array([1, 2, 3, 4, 5])

print("NumPy Array:")
print(arr)

NumPy Array:
[1 2 3 4 5]


In [8]:
import numpy as np
import tensorflow as tf

# NumPy array create karna
arr = np.array([1, 2, 3, 4, 5])

print("NumPy Array:")
arr

NumPy Array:


array([1, 2, 3, 4, 5])

In [9]:
np_arr = tf.constant(np.array([1, 2, 3, 4, 5]))
np_arr

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5])>

In [10]:
import numpy as np
import tensorflow as tf

# NumPy array create karna
arr = np.array([1, 2, 3, 4, 5])

print("NumPy Array:")
print(arr)

# TensorFlow tensor me convert karna
tensor = tf.constant(arr)

print("\nTensorFlow Tensor:")
print(tensor)

# TensorFlow se calculation
result = tensor * 2

print("\nTensorFlow Result (array * 2):")
print(result)

NumPy Array:
[1 2 3 4 5]

TensorFlow Tensor:
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)

TensorFlow Result (array * 2):
tf.Tensor([ 2  4  6  8 10], shape=(5,), dtype=int32)
