In [ ]:
tf.divide() TensorFlow me element-wise division (Python-style division) ke liye use hota hai. Ye x / y operator jaisa hi kaam karta hai.

In [1]:
import tensorflow as tf

In [3]:
import tensorflow as tf

x = tf.constant([16, 12, 11])
y = tf.constant([4, 6, 2])

result = tf.divide(x, y)
print(result)

tf.Tensor([4.  2.  5.5], shape=(3,), dtype=float64)


In [9]:
a = tf.constant([4.0, 6.0, 2.0])
b = tf.constant([2.0, 0.0, 0.0])

safe = tf.math.divide_no_nan(a, b)
print(safe)
# result: [2.0, 0.0, 0.0]

tf.Tensor([2. 0. 0.], shape=(3,), dtype=float32)


In [7]:
m = tf.constant([4.0, 6.0, 2.0])
n = tf.constant([2.0, 0.0, 0.0])

not_safe = tf.math.divide_no_nan(m, n)
print(not_safe)
# result: [2. 0. 0.]

tf.Tensor([2. 0. 0.], shape=(3,), dtype=float32)
