tf.subtract() TensorFlow me do tensors ko element-wise add minus ke liye use hota hai.
Ye x - y jaisa hi kaam karta hai, aur agar shapes compatible hon to broadcasting bhi follow karta hai.

In [2]:
import tensorflow as tf

In [3]:
a = 10
b = 5
tf.subtract(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [4]:
arr = [1,2,3,4]
arr2 = [5,6,7,8]
tf.subtract(arr, arr2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([-4, -4, -4, -4])>

In [5]:
tupleval = (1,2,3,4)
tupleval2 = (5,6,7,8)
tf.subtract(tupleval, tupleval2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([-4, -4, -4, -4])>

In [6]:
tf.subtract(arr, tupleval2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([-4, -4, -4, -4])>

In [7]:
tf.subtract(tupleval, b)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([-4, -3, -2, -1])>

In [8]:
c = [10,15]
tf.subtract(tupleval, c)

InvalidArgumentError: {{function_node __wrapped__Sub_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [4] vs. [2] [Op:Sub]