tf.add() TensorFlow me do tensors ko element-wise add karne ke liye use hota hai.
Ye x + y jaisa hi kaam karta hai, aur agar shapes compatible hon to broadcasting bhi follow karta hai.

In [1]:
import tensorflow as tf

In [3]:
a = 10
b = 5
tf.add(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=15>

In [4]:
arr = [1,2,3,4]
arr2 = [5,6,7,8]
tf.add(arr, arr2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 6,  8, 10, 12])>

In [5]:
tupleval = (1,2,3,4)
tupleval2 = (5,6,7,8)
tf.add(tupleval, tupleval2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 6,  8, 10, 12])>

In [6]:
tf.add(arr, tupleval2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 6,  8, 10, 12])>

In [8]:
tf.add(tupleval, b)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([6, 7, 8, 9])>

In [9]:
c = [10,15]
tf.add(tupleval, c)

InvalidArgumentError: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [4] vs. [2] [Op:AddV2] name: 