In [1]:
import numpy as np

In [2]:
zeros = np.zeros((2, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
ones = np.ones((2, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
arrange = np.arange(1, 11)
print(arrange)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
# with steps
with_steps = np.arange(0, 11, 2)
print(with_steps)

[ 0  2  4  6  8 10]


In [8]:
diagArr = np.diag([1,2,3,4])
print(diagArr);

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [9]:
diagArrRev = np.diag(diagArr)
print(diagArrRev);

[1 2 3 4]
